name: lintTestDeploy
on: workflow_dispatch
jobs:
  lintTestDeploy:
    runs-on: ubuntu-latest    
    steps:
    - name: lint
      run: echo "Linting"
    - name: test
      run: echo "Testing"
    - name: deploy
      run: echo "Deploying"