name: lintTestDeploy
on: workflow_dispatch
jobs:
  lintTestDeploy:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specify the Node.js version

    - name: Install dependencies
      run: npm install      
    
    - name: lint
      run: eslint --ext .jsx --fix src
    
    - name: test
      run: vitest run      
    
    - name: build
      run: vite build
    
    - name: deploy
      run: echo "Deploying"